// report.js — turns the registry into AUDIENCES.md.
//
// AUDIENCES.md is the file a person opens, and the file Claude reads first
// when someone asks "what audiences do we have". The JSON in data/ is the
// source of truth; this is the readable view of it. Regenerate it after any
// change — `tsf report` does that, and most commands call it for you.
//
// EDIT THIS FILE IF: you want the report to say something it does not say yet.
// Never edit AUDIENCES.md by hand — it is overwritten every time.

import fs from "node:fs";
import { PATHS } from "./config.js";
import { listAudiences, loadShows, readHistory } from "./registry.js";
import { checkReadiness } from "./audiences.js";

/** "2026-08-25T17:40:00.000Z" -> "2026-08-25" */
const day = (iso) => (iso || "").slice(0, 10);

/** 12345 -> "12,345" */
const num = (value) =>
  value === null || value === undefined ? "—" : Number(value).toLocaleString("en-US");

/** Renders a tiny text trend from a size history: "412 → 690 → 1,204". */
function trend(sizeHistory, limit = 4) {
  if (!sizeHistory?.length) return "—";
  const recent = sizeHistory.slice(-limit);
  const parts = recent.map((point) => num(point.size));
  const prefix = sizeHistory.length > limit ? "… → " : "";
  return prefix + parts.join(" → ");
}

export function buildReport() {
  const audiences = listAudiences();
  const shows = loadShows();
  const history = readHistory({ limit: 60 });
  const generatedAt = new Date().toISOString();

  const active = audiences.filter((a) => a.status === "active");
  const retired = audiences.filter((a) => a.status !== "active");
  const totalReach = active.reduce((sum, a) => sum + (a.sizeHistory.at(-1)?.size ?? 0), 0);

  const lines = [];

  lines.push("# Audiences");
  lines.push("");
  lines.push(
    "Generated by `tsf report` — do not edit by hand. The source of truth is " +
      "`data/audiences/*.json` and `data/history/*.jsonl`."
  );
  lines.push("");
  lines.push(`_Last generated: ${generatedAt.replace("T", " ").slice(0, 16)} UTC_`);
  lines.push("");
  lines.push(
    `**${active.length} active** · ${retired.length} retired · ` +
      `${num(totalReach)} contacts across active audiences · ${shows.length} shows tracked`
  );
  lines.push("");

  // ---- summary table -------------------------------------------------------
  lines.push("## All audiences");
  lines.push("");
  if (!audiences.length) {
    lines.push("_None yet. Create one with `tsf audience create`._");
  } else {
    lines.push("| Audience | Type | Shows | Reach | Trend | Destinations | Last checked |");
    lines.push("| --- | --- | --- | ---: | --- | --- | --- |");
    for (const audience of audiences) {
      const latest = audience.sizeHistory.at(-1);
      const isGeo = audience.type === "geo";
      const geoSpec = audience.definition?.geo;
      // The summary table is what gets scanned. A test destination shown here
      // as a plain "meta (live)" is read as fact and never questioned.
      const destinations = audience.destinations.length
        ? audience.destinations
            .map((d) => `${d.platform} (${d.status})${d.testMode ? " **[TEST]**" : ""}`)
            .join(", ")
        : "—";
      const flag = audience.status === "active" ? "" : " _(retired)_";
      lines.push(
        `| **${audience.name}**${flag}<br>\`${audience.id}\` ` +
          `| ${isGeo ? "geo" : "list"} ` +
          `| ${audience.shows.join(", ") || "—"} ` +
          `| ${isGeo ? `${geoSpec?.window?.totalDays ?? "?"} days at venue` : num(latest?.size)} ` +
          `| ${isGeo ? `${geoSpec?.window?.runStart} → ${geoSpec?.window?.runEnd}` : trend(audience.sizeHistory)} ` +
          `| ${destinations} ` +
          `| ${isGeo ? day(audience.createdAt) : day(latest?.at) || "never"} |`
      );
    }
  }
  lines.push("");

  // ---- per-audience detail -------------------------------------------------
  if (audiences.length) {
    lines.push("## Audience detail");
    lines.push("");
    for (const audience of audiences) {
      const latest = audience.sizeHistory.at(-1);
      lines.push(`### ${audience.name}`);
      lines.push("");
      lines.push(`- **ID:** \`${audience.id}\``);
      lines.push(`- **Status:** ${audience.status}`);
      lines.push(`- **Purpose:** ${audience.purpose || "_not recorded_"}`);
      lines.push(`- **Created:** ${day(audience.createdAt)} by ${audience.createdBy}`);
      lines.push(`- **Type:** ${audience.type === "geo" ? "geo — a place and a time window, no contact data" : "list — contacts we hold details for"}`);
      lines.push(`- **Shows:** ${audience.shows.join(", ") || "—"}`);

      if (audience.type === "geo") {
        const spec = audience.definition?.geo;
        if (spec) {
          lines.push(`- **Venue:** ${spec.venue.name} (${spec.venue.lat}, ${spec.venue.lng})`);
          lines.push(
            `- **Run window:** ${spec.window.runStart} → ${spec.window.runEnd} ` +
              `(${spec.window.totalDays} days — show runs ${spec.window.showStart} → ${spec.window.showEnd})`
          );
          lines.push("");
          lines.push("| Ring | Radius | What it covers |");
          lines.push("| --- | ---: | --- |");
          for (const ring of spec.rings) {
            lines.push(`| ${ring.name} | ${ring.radiusMiles} mi / ${ring.radiusKm} km | ${ring.note} |`);
          }
          lines.push("");
          lines.push(`> **Presence setting:** ${spec.presenceSetting}`);
        }
        lines.push("");
      } else {
        lines.push(`- **HubSpot list:** ${audience.hubspotListId ?? "_none_"}`);
        lines.push(`- **Sources:** ${audience.sources.join(", ") || "—"}`);
        lines.push(`- **Current size:** ${num(latest?.size)} (measured ${day(latest?.at) || "never"})`);
        lines.push("");
      }

      if (audience.type !== "geo" && audience.sizeHistory.length > 1) {
        lines.push("**Size over time**");
        lines.push("");
        lines.push("| Date | Size | Change | Note |");
        lines.push("| --- | ---: | ---: | --- |");
        audience.sizeHistory.forEach((point, index) => {
          const previous = index > 0 ? audience.sizeHistory[index - 1].size : null;
          const delta = previous === null ? "—" : (point.size - previous >= 0 ? "+" : "") + num(point.size - previous);
          lines.push(`| ${day(point.at)} | ${num(point.size)} | ${delta} | ${point.note || ""} |`);
        });
        lines.push("");
      }

      if (audience.destinations.length) {
        lines.push("**Where it is used**");
        lines.push("");
        lines.push("| Platform | Status | External ID | Notes | Updated |");
        lines.push("| --- | --- | --- | --- | --- |");
        for (const destination of audience.destinations) {
          lines.push(
            `| ${destination.platform} | ${destination.status}${
              destination.testMode ? " **[TEST]**" : ""
            } | ${destination.externalId || "—"} ` +
              `| ${destination.notes || ""} | ${day(destination.updatedAt)} |`
          );
        }
        lines.push("");
      }

      // Readiness against platform floors — the "why won't this deliver" answer.
      if (audience.type !== "geo" && latest?.size) {
        const readiness = checkReadiness(audience);
        const problems = readiness.findings.filter((f) => f.level !== "ok");
        if (problems.length) {
          lines.push("**Heads up**");
          lines.push("");
          for (const problem of problems) {
            lines.push(`- \`${problem.platform}\` — ${problem.message}`);
          }
          lines.push("");
        }
      }

      if (audience.notes.length) {
        lines.push("**Notes**");
        lines.push("");
        for (const note of audience.notes) {
          lines.push(`- _${day(note.at)}_ (${note.actor}): ${note.text}`);
        }
        lines.push("");
      }
    }
  }

  // ---- shows ---------------------------------------------------------------
  lines.push("## Shows");
  lines.push("");
  if (!shows.length) {
    lines.push("_None yet. Add one with `tsf show add`._");
  } else {
    lines.push("| Show | ID | Dates | Venue (for geo targeting) | HubSpot form IDs |");
    lines.push("| --- | --- | --- | --- | --- |");
    for (const show of shows) {
      const venue = show.venue
        ? `${show.venue.name} — ${show.venue.lat}, ${show.venue.lng}`
        : `_not researched — run \`tsf show research --id ${show.id}\`_`;
      lines.push(
        `| ${show.name}${show.testMode ? " **[TEST]**" : ""} | \`${show.id}\` | ${show.startDate} → ${show.endDate} ` +
          `| ${venue} | ${show.formIds?.join(", ") || "_none linked_"} |`
      );
    }
  }
  lines.push("");

  // ---- history -------------------------------------------------------------
  lines.push("## Recent activity");
  lines.push("");
  lines.push(
    "Newest first. The full log lives in `data/history/*.jsonl` — this is the " +
      "last 60 entries. Rows marked **[TEST]** were run with test mode on: they " +
      "changed nothing outside this machine and must not be counted as real."
  );
  lines.push("");
  if (!history.length) {
    lines.push("_Nothing logged yet._");
  } else {
    lines.push("| When | Who | What | Detail |");
    lines.push("| --- | --- | --- | --- |");
    for (const entry of history) {
      // A test run has to be unmistakable in the artifact people actually read.
      // It is not hidden — a log that omits runs misleads too — but it must
      // never be mistakable for something that really happened.
      const detail = entry.testMode
        ? `**[TEST — did not really happen]** ${describeEntry(entry)}`
        : describeEntry(entry);

      lines.push(
        `| ${entry.at.replace("T", " ").slice(0, 16)} | ${entry.actor} ` +
          `| \`${entry.action}\` | ${detail} |`
      );
    }
  }
  lines.push("");

  return lines.join("\n");
}

/** One-line plain English for a history entry. Keep it short — it is a cell. */
function describeEntry(entry) {
  switch (entry.action) {
    case "audience.created":
      if (entry.type === "geo") {
        return `**${entry.audienceName}** (geo) — ${entry.venue}, ${entry.runStart} → ${entry.runEnd}`;
      }
      return `**${entry.audienceName}** — shows: ${(entry.shows || []).join(", ") || "—"}, list ${entry.hubspotListId ?? "?"}`;
    case "show.researched":
      return `**${entry.showName}** venue set to ${entry.venue} (${entry.lat}, ${entry.lng})`;
    case "audience.refreshed": {
      const delta = entry.delta === null || entry.delta === undefined
        ? ""
        : ` (${entry.delta >= 0 ? "+" : ""}${num(entry.delta)})`;
      return `**${entry.audienceName}** now ${num(entry.size)}${delta} ${entry.note ? `— ${entry.note}` : ""}`;
    }
    case "audience.destination_set":
      return `**${entry.audienceName}** → ${entry.platform} is *${entry.status}*${entry.notes ? ` — ${entry.notes}` : ""}`;
    case "audience.retired":
      return `**${entry.audienceName}** retired at ${num(entry.finalSize)}${entry.reason ? ` — ${entry.reason}` : ""}`;
    case "import.committed":
      return `${entry.file} → ${entry.showId} / ${entry.source}: ${num(entry.created)} created, ${num(entry.updated)} updated, ${num(entry.rejected)} rejected`;
    case "show.created":
      return `**${entry.showName}** (${entry.startDate} → ${entry.endDate})`;
    case "note":
      return `**${entry.audienceName}**: ${entry.text}`;
    default:
      return JSON.stringify(entry).slice(0, 160);
  }
}

export function writeReport() {
  const markdown = buildReport();
  fs.writeFileSync(PATHS.report, markdown, "utf8");
  return PATHS.report;
}
